export type Product = { id:string; name:string; category:string; relatedGroup:string; price:string; oldPrice?:string; rating:string; reviews:string; image:string; description:string; dimensions:string[]; material:string; colors:string[] };
const item=(id:string,name:string,category:string,relatedGroup:string,price:string,image:string,description:string,dimensions:string[],material:string,colors:string[],rating='4.8',reviews='48',oldPrice?:string):Product=>({id,name,category,relatedGroup,price,image,description,dimensions,material,colors,rating,reviews,oldPrice});

export const catalog: Product[] = [
 item('luna-sofa','Luna Sofa 3 Seater','Ruang Tamu','sofa','Rp 7.499.000','/images/products/product1.jpg','Sofa tiga dudukan dengan proporsi santai dan bantalan empuk untuk ruang keluarga modern.',['Lebar 210 cm','Dalam 92 cm','Tinggi 82 cm'],'Kain woven, kayu solid, busa high density',['Sand','Abu muda'],'4.9','124','Rp 8.250.000'),
 item('mira-sofa','Mira Sofa 2 Seater','Ruang Tamu','sofa','Rp 5.299.000','/images/categories/living.jpg','Sofa dua dudukan yang ringkas untuk apartemen dan sudut baca.',['Lebar 168 cm','Dalam 88 cm','Tinggi 80 cm'],'Kain woven dan kaki kayu solid',['Ivory','Abu muda'],'4.8','77'),
 item('nara-sofa','Nara Sofa L-Shape','Ruang Tamu','sofa','Rp 9.899.000','/images/products/product1.jpg','Sofa sudut lapang untuk duduk bersama tanpa membuat komposisi ruang terasa berat.',['Lebar 280 cm','Dalam 165 cm','Tinggi 84 cm'],'Kain polyester dan rangka kayu',['Greige','Abu batu'],'4.9','63','Rp 10.750.000'),
 item('arka-dining','Arka Meja Makan Set 4 Kursi','Ruang Makan','dining-table','Rp 5.999.000','/images/products/product2.jpg','Set meja makan ringkas untuk empat orang, dibuat agar mudah menyatu dengan ruang makan sehari-hari.',['Panjang 140 cm','Lebar 80 cm','Tinggi 75 cm'],'Kayu engineered dan veneer oak',['Natural oak','Walnut muda'],'4.8','86'),
 item('tama-dining','Tama Meja Makan 6 Kursi','Ruang Makan','dining-table','Rp 8.499.000','/images/categories/dining.jpg','Meja makan enam kursi dengan garis sederhana untuk jamuan keluarga.',['Panjang 180 cm','Lebar 90 cm','Tinggi 75 cm'],'Veneer oak dan kayu solid',['Natural oak','Walnut'],'4.7','55'),
 item('kaya-dining','Kaya Meja Makan Bundar','Ruang Makan','dining-table','Rp 4.299.000','/images/products/product2.jpg','Meja makan bundar yang membantu percakapan terasa lebih dekat di ruang terbatas.',['Diameter 110 cm','Tinggi 75 cm'],'Kayu engineered dan veneer',['Oak terang','Putih'],'4.8','41'),
 item('evora-bed','Evora Bed Frame Queen Size','Kamar Tidur','bed','Rp 6.999.000','/images/products/product3.jpg','Rangka tempat tidur queen dengan kepala ranjang berlapis kain yang membuat kamar tetap terasa tenang.',['Untuk kasur 160 x 200 cm','Lebar 172 cm','Tinggi 112 cm'],'Kayu solid, kain polyester, busa',['Beige','Abu kabut'],'4.9','72','Rp 7.500.000'),
 item('alva-bed','Alva Bed Frame King Size','Kamar Tidur','bed','Rp 8.799.000','/images/categories/bedroom.jpg','Rangka king size dengan kepala ranjang berlapis untuk kamar yang terasa hangat dan rapi.',['Untuk kasur 180 x 200 cm','Lebar 192 cm','Tinggi 112 cm'],'Kayu solid dan kain woven',['Krem','Abu muda'],'4.8','48'),
 item('sena-bed','Sena Bed Frame Single','Kamar Tidur','bed','Rp 3.499.000','/images/products/product3.jpg','Rangka single yang proporsional untuk kamar remaja atau ruang tidur tamu.',['Untuk kasur 100 x 200 cm','Lebar 112 cm','Tinggi 98 cm'],'Kayu engineered dan kain',['Putih','Natural'],'4.7','36'),
 item('nexis-chair','Nexis Kursi Kantor Ergonomis','Ruang Kerja','office-chair','Rp 2.499.000','/images/products/product9.jpg','Kursi kerja dengan dukungan punggung yang dapat disesuaikan untuk rutinitas kerja yang lebih nyaman.',['Lebar 64 cm','Dalam 65 cm','Tinggi 108-118 cm'],'Mesh breathable, metal powder coated',['Hitam','Abu'],'4.7','106'),
 item('ora-chair','Ora Kursi Kerja Mesh','Ruang Kerja','office-chair','Rp 1.899.000','/images/categories/office.jpg','Kursi kerja mesh dengan dudukan berlapis untuk meja kerja di rumah.',['Lebar 60 cm','Dalam 61 cm','Tinggi 102-112 cm'],'Mesh dan metal powder coated',['Hitam','Abu muda'],'4.7','62'),
 item('vesta-chair','Vesta Kursi Direktur','Ruang Kerja','office-chair','Rp 3.799.000','/images/products/product9.jpg','Kursi direktur dengan sandaran tinggi dan penyesuaian dudukan yang praktis.',['Lebar 68 cm','Dalam 70 cm','Tinggi 116-126 cm'],'Kulit sintetis dan metal',['Hitam','Cokelat tua'],'4.8','39'),
 item('lento-desk','Lento Meja Kerja 120 cm','Ruang Kerja','desk','Rp 2.799.000','/images/products/product4.jpg','Meja kerja lurus untuk laptop, monitor, dan perlengkapan kerja sehari-hari.',['Panjang 120 cm','Dalam 60 cm','Tinggi 75 cm'],'Kayu engineered dan kaki metal',['Oak','Putih'],'4.8','71'),
 item('sora-desk','Sora Meja Kerja dengan Laci','Ruang Kerja','desk','Rp 3.499.000','/images/categories/office.jpg','Meja kerja dengan laci tertutup agar kabel dan alat tulis tidak mengganggu area kerja.',['Panjang 140 cm','Dalam 65 cm','Tinggi 75 cm'],'Veneer oak dan metal',['Oak terang','Abu'],'4.9','44'),
 item('niko-desk','Niko Meja Kerja Sudut','Ruang Kerja','desk','Rp 4.299.000','/images/products/product4.jpg','Meja sudut yang memaksimalkan area kerja tanpa memenuhi ruangan.',['Panjang 150 cm','Dalam 120 cm','Tinggi 75 cm'],'Kayu engineered dan rangka baja',['Walnut','Hitam'],'4.7','31'),
 item('kana-cabinet','Kana Lemari Penyimpanan','Penyimpanan','cabinet','Rp 3.999.000','/images/products/product5.jpg','Lemari penyimpanan modular dengan pintu tertutup untuk menjaga ruang tetap rapi.',['Lebar 120 cm','Dalam 42 cm','Tinggi 185 cm'],'Papan engineered, kaki metal',['Putih','Oak terang'],'4.8','59','Rp 4.450.000'),
 item('mori-wardrobe','Mori Lemari Pakaian','Kamar Tidur','wardrobe','Rp 6.499.000','/images/products/product5.jpg','Lemari pakaian berkapasitas besar dengan susunan gantung dan rak untuk kebutuhan harian.',['Lebar 160 cm','Dalam 56 cm','Tinggi 200 cm'],'Papan engineered, finishing melamine',['Putih','Natural'],'4.9','68','Rp 7.000.000'),
 item('riko-coffee','Riko Meja Kopi Round','Ruang Tamu','coffee-table','Rp 2.999.000','/images/products/product6.jpg','Meja kopi bundar dengan bentuk lembut yang mudah dipadukan pada ruang tamu kontemporer.',['Diameter 85 cm','Tinggi 38 cm'],'Kayu veneer dan metal',['Oak','Hitam'],'4.8','44'),
 item('hana-shelf','Hana Rak Buku','Penyimpanan','shelf','Rp 2.499.000','/images/products/product7.jpg','Rak terbuka empat tingkat untuk buku, dekorasi, atau perlengkapan kerja di rumah.',['Lebar 80 cm','Dalam 35 cm','Tinggi 160 cm'],'Kayu engineered dan rangka baja',['Oak','Putih'],'4.7','91'),
 item('sora-rug','Sora Karpet 160 x 230 cm','Dekorasi Rumah','rug','Rp 1.299.000','/images/products/product10.jpg','Karpet lembut bernuansa netral untuk menyatukan komposisi ruang keluarga atau kamar tidur.',['160 x 230 cm','Tebal 12 mm'],'Polyester woven',['Ivory','Abu muda'],'4.8','39'),
 item('arli-lamp','Arli Lampu Meja','Pencahayaan','table-lamp','Rp 899.000','/images/products/product4.jpg','Lampu meja dengan cahaya hangat untuk sudut baca dan meja samping tempat tidur.',['Diameter 22 cm','Tinggi 48 cm'],'Metal dan kain',['Krem','Putih'],'4.7','53')
];
export const productById=(id:string)=>catalog.find((p)=>p.id===id);
export const relatedProducts=(product:Product)=>catalog.filter((p)=>p.relatedGroup===product.relatedGroup&&p.id!==product.id).slice(0,4);
export const categories=['Ruang Tamu','Kamar Tidur','Ruang Makan','Ruang Kerja','Penyimpanan','Pencahayaan','Dekorasi Rumah'];
