export type Product = { id:string; name:string; category:string; price:string; oldPrice?:string; rating:string; reviews:string; image:string; description:string; dimensions:string[]; material:string; colors:string[] };

export const catalog: Product[] = [
 {id:'luna-sofa',name:'Luna Sofa 3 Seater',category:'Ruang Tamu',price:'Rp 7.499.000',oldPrice:'Rp 8.250.000',rating:'4.9',reviews:'124',image:'/images/products/product1.jpg',description:'Sofa tiga dudukan dengan proporsi santai dan bantalan empuk untuk ruang keluarga modern.',dimensions:['Lebar 210 cm','Dalam 92 cm','Tinggi 82 cm'],material:'Kain woven, kayu solid, busa high density',colors:['Sand','Abu muda']},
 {id:'arka-dining',name:'Arka Meja Makan Set 4 Kursi',category:'Ruang Makan',price:'Rp 5.999.000',rating:'4.8',reviews:'86',image:'/images/products/product2.jpg',description:'Set meja makan ringkas untuk empat orang, dibuat agar mudah menyatu dengan ruang makan sehari-hari.',dimensions:['Panjang 140 cm','Lebar 80 cm','Tinggi 75 cm'],material:'Kayu engineered dan veneer oak',colors:['Natural oak','Walnut muda']},
 {id:'evora-bed',name:'Evora Bed Frame Queen Size',category:'Kamar Tidur',price:'Rp 6.999.000',oldPrice:'Rp 7.500.000',rating:'4.9',reviews:'72',image:'/images/products/product3.jpg',description:'Rangka tempat tidur queen dengan kepala ranjang berlapis kain yang membuat kamar tetap terasa tenang.',dimensions:['Untuk kasur 160 x 200 cm','Lebar 172 cm','Tinggi 112 cm'],material:'Kayu solid, kain polyester, busa',colors:['Beige','Abu kabut']},
 {id:'nexis-chair',name:'Nexis Kursi Kantor Ergonomis',category:'Ruang Kerja',price:'Rp 2.499.000',rating:'4.7',reviews:'106',image:'/images/products/product9.jpg',description:'Kursi kerja dengan dukungan punggung yang dapat disesuaikan untuk rutinitas kerja yang lebih nyaman.',dimensions:['Lebar 64 cm','Dalam 65 cm','Tinggi 108-118 cm'],material:'Mesh breathable, metal powder coated',colors:['Hitam','Abu']},
 {id:'kana-cabinet',name:'Kana Lemari Penyimpanan',category:'Penyimpanan',price:'Rp 3.999.000',oldPrice:'Rp 4.450.000',rating:'4.8',reviews:'59',image:'/images/products/product5.jpg',description:'Lemari penyimpanan modular dengan pintu tertutup untuk menjaga ruang tetap rapi.',dimensions:['Lebar 120 cm','Dalam 42 cm','Tinggi 185 cm'],material:'Papan engineered, kaki metal',colors:['Putih','Oak terang']},
 {id:'riko-coffee',name:'Riko Meja Kopi Round',category:'Ruang Tamu',price:'Rp 2.999.000',rating:'4.8',reviews:'44',image:'/images/products/product6.jpg',description:'Meja kopi bundar dengan bentuk lembut yang mudah dipadukan pada ruang tamu kontemporer.',dimensions:['Diameter 85 cm','Tinggi 38 cm'],material:'Kayu veneer dan metal',colors:['Oak','Hitam']},
 {id:'hana-shelf',name:'Hana Rak Buku',category:'Penyimpanan',price:'Rp 2.499.000',rating:'4.7',reviews:'91',image:'/images/products/product7.jpg',description:'Rak terbuka empat tingkat untuk buku, dekorasi, atau perlengkapan kerja di rumah.',dimensions:['Lebar 80 cm','Dalam 35 cm','Tinggi 160 cm'],material:'Kayu engineered dan rangka baja',colors:['Oak','Putih']},
 {id:'mori-wardrobe',name:'Mori Lemari Pakaian',category:'Kamar Tidur',price:'Rp 6.499.000',oldPrice:'Rp 7.000.000',rating:'4.9',reviews:'68',image:'/images/products/product5.jpg',description:'Lemari pakaian berkapasitas besar dengan susunan gantung dan rak untuk kebutuhan harian.',dimensions:['Lebar 160 cm','Dalam 56 cm','Tinggi 200 cm'],material:'Papan engineered, finishing melamine',colors:['Putih','Natural']},
 {id:'sora-rug',name:'Sora Karpet 160 x 230 cm',category:'Dekorasi Rumah',price:'Rp 1.299.000',rating:'4.8',reviews:'39',image:'/images/products/product10.jpg',description:'Karpet lembut bernuansa netral untuk menyatukan komposisi ruang keluarga atau kamar tidur.',dimensions:['160 x 230 cm','Tebal 12 mm'],material:'Polyester woven',colors:['Ivory','Abu muda']},
 {id:'arli-lamp',name:'Arli Lampu Meja',category:'Pencahayaan',price:'Rp 899.000',rating:'4.7',reviews:'53',image:'/images/categories/decor.jpg',description:'Lampu meja dengan cahaya hangat untuk sudut baca dan meja samping tempat tidur.',dimensions:['Diameter 22 cm','Tinggi 48 cm'],material:'Metal dan kain',colors:['Krem','Putih']}
];
export const productById=(id:string)=>catalog.find((p)=>p.id===id);
export const categories=['Ruang Tamu','Kamar Tidur','Ruang Makan','Ruang Kerja','Penyimpanan','Pencahayaan','Dekorasi Rumah'];
export const rupiah=(value:string)=>value;
