"use client";

import Image from "next/image";
import Link from "next/link";
import { FormEvent, ReactNode, useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { ArrowLeft, ArrowRight, Check, Heart, Menu, Microscope, Minus, Plus, Search, ShoppingBag, SlidersHorizontal, Star, Trash2, UserRound, X } from "lucide-react";
import { uniqueCatalog, Product } from "@/lib/catalog";

type CartLine={id:string; quantity:number};
const readStore=<T,>(key:string):T=>{if(typeof window==='undefined')return [] as T;try{return JSON.parse(sessionStorage.getItem(key)||'[]') as T}catch{return [] as T}};
export function useStore(){const [cart,setCart]=useState<CartLine[]>([]);const [wishes,setWishes]=useState<string[]>([]);const [notice,setNotice]=useState('');const [hydrated,setHydrated]=useState(false);useEffect(()=>{
  // eslint-disable-next-line react-hooks/set-state-in-effect -- syncing from browser-only sessionStorage after mount to avoid SSR/client hydration mismatch
  setCart(readStore<CartLine[]>('better-space-cart'));
  setWishes(readStore<string[]>('better-space-wishes'));
  setHydrated(true);
},[]);const saveCart=(next:CartLine[])=>{setCart(next);sessionStorage.setItem('better-space-cart',JSON.stringify(next))};const saveWishes=(next:string[])=>{setWishes(next);sessionStorage.setItem('better-space-wishes',JSON.stringify(next))};const add=(id:string)=>{const exists=cart.find(x=>x.id===id);saveCart(exists?cart.map(x=>x.id===id?{...x,quantity:x.quantity+1}:x):[...cart,{id,quantity:1}]);setNotice(`${uniqueCatalog.find(x=>x.id===id)?.name} ditambahkan ke keranjang.`);setTimeout(()=>setNotice(''),2500)};const remove=(id:string)=>saveCart(cart.filter(x=>x.id!==id));const quantity=(id:string,delta:number)=>saveCart(cart.map(x=>x.id===id?{...x,quantity:Math.max(1,x.quantity+delta)}:x));const toggle=(id:string)=>saveWishes(wishes.includes(id)?wishes.filter(x=>x!==id):[...wishes,id]);return{cart,wishes,notice,setNotice,add,remove,quantity,toggle,hydrated}}
export type Store=ReturnType<typeof useStore>;

export function StoreHeader({store}:{store:Store}){const [open,setOpen]=useState(false);const [query,setQuery]=useState("");const router=useRouter();const total=store.cart.reduce((n,x)=>n+x.quantity,0);const submit=(e:FormEvent)=>{e.preventDefault();const hit=uniqueCatalog.find(p=>p.name.toLowerCase().includes(query.toLowerCase()));if(hit)router.push(`/products/${hit.id}`);else store.setNotice("Produk belum ditemukan. Coba kata kunci lain.")};return <><header className="store-header"><div className="store-shell header-inner"><button className="mobile-toggle" aria-label="Buka menu" onClick={()=>setOpen(true)}><Menu/></button><Link href="/" className="store-mark">Better Space<small>FURNITURE UNTUK KEHIDUPAN YANG LEBIH BAIK.</small></Link><form className="store-search" onSubmit={submit}><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Cari furniture, ruangan, atau gaya..." aria-label="Cari produk"/><button aria-label="Cari"><Search size={18}/></button></form><nav className="store-actions"><Link href="/wishlist"><Heart size={19}/><span>Wishlist</span>{store.wishes.length>0&&<b>{store.wishes.length}</b>}</Link><Link href="/cart"><ShoppingBag size={19}/><span>Keranjang</span>{total>0&&<b>{total}</b>}</Link><Link href="/account"><UserRound size={19}/><span>Akun</span></Link></nav></div></header><nav className="store-nav"><div className="store-shell"><Link href="/products">Semua Produk</Link><Link href="/products?category=Ruang%20Tamu">Ruang Tamu</Link><Link href="/products?category=Kamar%20Tidur">Kamar Tidur</Link><Link href="/products?category=Ruang%20Makan">Ruang Makan</Link><Link href="/products?category=Ruang%20Kerja">Ruang Kerja</Link><Link href="/products?category=Penyimpanan">Penyimpanan</Link><Link href="/products?category=Dekorasi%20Rumah">Dekorasi</Link></div></nav>{open&&<div className="store-drawer" role="dialog" aria-modal="true" aria-label="Navigasi Better Space"><div><button aria-label="Tutup menu" onClick={()=>setOpen(false)}><X/></button><Link href="/" className="store-mark">Better Space<small>FURNITURE UNTUK KEHIDUPAN YANG LEBIH BAIK.</small></Link>{['Semua Produk','Ruang Tamu','Kamar Tidur','Ruang Makan','Ruang Kerja','Penyimpanan','Dekorasi Rumah'].map(x=><Link key={x} href={x==='Semua Produk'?'/products':`/products?category=${encodeURIComponent(x)}`} onClick={()=>setOpen(false)}>{x}<ArrowRight size={16}/></Link>)}</div></div>}{store.notice&&<p className="store-toast" role="status"><Check size={16}/>{store.notice}</p>}</>}

export function ProductCard({product,store}:{product:Product;store:Store}){const saved=store.wishes.includes(product.id);return <article className="catalog-card"><Link href={`/products/${product.id}`} className="catalog-image"><Image src={product.image} fill sizes="(max-width: 650px) 50vw, (max-width: 950px) 33vw, 25vw" alt={product.name}/></Link><button className={`wish ${saved?'saved':''}`} aria-label={saved?`Hapus ${product.name} dari wishlist`:`Simpan ${product.name} ke wishlist`} aria-pressed={saved} onClick={()=>store.toggle(product.id)}><Heart size={17} fill={saved?'currentColor':'none'}/></button><div className="catalog-copy"><p>{product.category}</p><Link href={`/products/${product.id}`}><h3>{product.name}</h3></Link><span className="catalog-rating"><Star size={13} fill="currentColor"/> {product.rating} <small>({product.reviews})</small></span><strong>{product.price}</strong><del aria-hidden={!product.oldPrice}>{product.oldPrice||" "}</del><button className="catalog-add" onClick={()=>store.add(product.id)}>Tambah <ShoppingBag size={15}/></button></div></article>}
export function StoreFooter(){return <footer className="store-footer"><div className="store-shell footer-columns"><div><Link href="/" className="store-mark">Better Space<small>FURNITURE UNTUK KEHIDUPAN YANG LEBIH BAIK.</small></Link><p>Furniture yang terhubung untuk setiap ruang, dari pilihan pertama hingga pesanan Anda.</p></div><div><h3>Belanja</h3><Link href="/products">Semua Produk</Link><Link href="/wishlist">Wishlist</Link><Link href="/cart">Keranjang</Link></div><div><h3>Layanan</h3><Link href="/account">Akun Saya</Link><Link href="/orders">Pesanan Saya</Link><Link href="/products">Bantuan Produk</Link></div></div><div className="store-shell store-footer-legal"><span>© 2026 Better Space. Semua hak dilindungi.</span><a href="#kebijakan-privasi">Kebijakan Privasi</a></div></footer>}
export function PageTitle({kicker,title,children}:{kicker:string;title:string;children?:ReactNode}){return <section className="page-heading"><div className="store-shell"><Link href="/" className="crumb"><ArrowLeft size={15}/> Kembali ke Better Space</Link><p>{kicker}</p><h1>{title}</h1>{children}</div></section>}
export function CartPanel({store}:{store:Store}){const lines=store.cart.map(x=>({line:x,product:uniqueCatalog.find(p=>p.id===x.id)!}));const total=lines.reduce((sum,x)=>sum+Number(x.product.price.replace(/\D/g,''))*x.line.quantity,0);return <div className="cart-panel">{!lines.length?<div className="empty-panel"><ShoppingBag/><h2>Keranjang Anda masih kosong</h2><p>Pilih furniture yang cocok, kemudian tambahkan ke keranjang.</p><Link href="/products">Lihat produk</Link></div>:<><div className="cart-lines">{lines.map(({line,product})=><article key={product.id}><Image src={product.image} width={110} height={110} alt={product.name}/><div><p>{product.category}</p><h3>{product.name}</h3><strong>{product.price}</strong><div className="quantity"><button aria-label={`Kurangi ${product.name}`} onClick={()=>store.quantity(product.id,-1)}><Minus size={14}/></button><span>{line.quantity}</span><button aria-label={`Tambah ${product.name}`} onClick={()=>store.quantity(product.id,1)}><Plus size={14}/></button></div></div><button className="delete" aria-label={`Hapus ${product.name}`} onClick={()=>store.remove(product.id)}><Trash2 size={18}/></button></article>)}</div><aside className="summary"><h2>Ringkasan Pesanan</h2><p><span>Subtotal</span><strong>Rp {total.toLocaleString('id-ID')}</strong></p><p><span>Pengiriman</span><span>Dihitung saat pembayaran</span></p><hr/><p className="summary-total"><span>Total</span><strong>Rp {total.toLocaleString('id-ID')}</strong></p><button onClick={()=>store.setNotice('Checkout belum tersedia dalam preview. Pesanan Anda tetap tersimpan di keranjang.')}>Lanjut ke Pembayaran <ArrowRight size={16}/></button></aside></>}</div>}
export function FilterBar({category,setCategory}:{category:string;setCategory:(x:string)=>void}){return <div className="filter-bar"><span className="filter-icon" aria-label="Penyaring produk"><Microscope size={17}/></span><SlidersHorizontal size={17}/><label>Kategori<select value={category} onChange={e=>setCategory(e.target.value)}><option value="">Semua kategori</option>{[...new Set(uniqueCatalog.map(x=>x.category))].map(x=><option key={x}>{x}</option>)}</select></label></div>}
