"use client";
import Image from "next/image";
import Link from "next/link";
import { FormEvent, useMemo, useState } from "react";
import { ArrowRight, Building2, ChevronDown, ChevronRight, CreditCard, Headphones, Heart, House, Menu, PackageCheck, Search, Send, ShoppingBag, Star, Truck, UserRound, Wrench, X } from "lucide-react";
import { uniqueCatalog } from "@/lib/catalog";
import { useStore } from "@/app/furniture/FurnitureShell";

const cat=(name:string, href:string)=>({name,href});
const categories=[cat("Sofa & Kursi Santai","/products?category=Ruang%20Tamu"),cat("Tempat Tidur & Kasur","/products?category=Kamar%20Tidur"),cat("Meja Makan & Kursi","/products?category=Ruang%20Makan"),cat("Lemari & Penyimpanan","/products?category=Penyimpanan"),cat("Meja Kerja & Kursi Kantor","/products?category=Ruang%20Kerja"),cat("Rak & Bookshelf","/products?category=Penyimpanan"),cat("Pencahayaan","/products?category=Pencahayaan"),cat("Karpet & Permadani","/products?category=Dekorasi%20Rumah"),cat("Dekorasi Rumah","/products?category=Dekorasi%20Rumah"),cat("Furniture Outdoor","/products"),cat("Furniture Anak","/products?category=Kamar%20Tidur"),cat("Promo & Clearance","/products")];
const nav=[cat("Semua Kategori","/products"),cat("Ruang Tamu","/products?category=Ruang%20Tamu"),cat("Kamar Tidur","/products?category=Kamar%20Tidur"),cat("Ruang Makan","/products?category=Ruang%20Makan"),cat("Ruang Kerja","/products?category=Ruang%20Kerja"),cat("Penyimpanan","/products?category=Penyimpanan"),cat("Pencahayaan","/products?category=Pencahayaan"),cat("Dekorasi Rumah","/products?category=Dekorasi%20Rumah")];
const categoryCards=[
 ["Sofa & Kursi Santai","/images/categories/living.jpg","/products?category=Ruang%20Tamu"],["Tempat Tidur","/images/categories/bedroom.jpg","/products?category=Kamar%20Tidur"],["Meja Makan & Kursi","/images/categories/dining.jpg","/products?category=Ruang%20Makan"],["Meja Kerja & Kursi","/images/categories/office.jpg","/products?category=Ruang%20Kerja"],["Lemari & Penyimpanan","/images/categories/storage.jpg","/products?category=Penyimpanan"],["Dekorasi Rumah","/images/categories/decor.jpg","/products?category=Dekorasi%20Rumah"],
] as const;
const tiles=["Sofa Minimalis","Meja Kopi","Lemari TV","Rak Dinding","Meja Kerja","Kursi Kantor","Lemari Arsip","Aksesoris Kantor"];
const productIds=["luna-sofa","arka-dining","bed-frame-evora-queen","office-chair-swara-ergo-highback","cabinet-biru-tall","coffee-table-riko-round","bookshelf-hana-4tier","wardrobe-ambar-3-door","rug-sora-160x230","table-lamp-arli-ceramic"];
const productSet=productIds.map(id=>uniqueCatalog.find(p=>p.id===id)).filter(Boolean) as typeof uniqueCatalog;
function Head({title,action,href="/products"}:{title:string;action?:string;href?:string}){return <div className="m-head"><h2>{title}</h2>{action&&<Link href={href}>{action} <ArrowRight size={14}/></Link>}</div>}
export default function HomeMarketplace(){
 const store=useStore(); const [menu,setMenu]=useState(false); const [tab,setTab]=useState("Terlaris"); const [query,setQuery]=useState(""); const [quote,setQuote]=useState(false); const [newsletter,setNewsletter]=useState(false); const cartCount=store.cart.reduce((n,x)=>n+x.quantity,0);
 const recommended=useMemo(()=>{const preferred=tab==="Produk Baru"?uniqueCatalog.filter(p=>p.isNew):tab==="Penawaran Spesial"?uniqueCatalog.filter(p=>p.oldPrice):productSet;const source=[...preferred,...uniqueCatalog.filter(p=>!preferred.some(choice=>choice.id===p.id))];return source.filter(p=>p.name.toLowerCase().includes(query.toLowerCase())).slice(0,10)},[tab,query]);
 const submitSearch=(e:FormEvent)=>{e.preventDefault();document.querySelector("#recommendations")?.scrollIntoView({behavior:"smooth"})};
 return <main className="market-home"><a className="market-skip" href="#market-content">Lewati ke konten</a>{store.notice&&<div className="market-toast" role="status">{store.notice}</div>}
 <div className="market-utility"><div className="market-shell"><span><Truck size={13}/>Gratis Ongkir untuk pembelian di atas Rp 1.000.000</span><nav><a href="#market-footer">Pusat Bantuan</a><Link href="/orders">Lacak Pesanan</Link><a href="#regions">Lokasi Toko</a><button type="button">Bahasa Indonesia <ChevronDown size={12}/></button></nav></div></div>
 <header className="market-header"><div className="market-shell"><button className="market-menu" onClick={()=>setMenu(true)} aria-label="Buka menu"><Menu/></button><Link href="/" className="market-brand">Casen Living<small>WHERE SPACE BECOMES HOME</small></Link><form className="market-search" onSubmit={submitSearch}><button type="button">Semua Kategori <ChevronDown size={12}/></button><input aria-label="Cari produk" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Cari furniture, ruangan, atau gaya..."/><button aria-label="Cari"><Search size={18}/></button></form><div className="market-actions"><Link href="/account"><UserRound/><span>Masuk<b>Akun Saya</b></span></Link><Link href="/wishlist"><Heart/><span>Wishlist<b>{store.wishes.length} Produk</b></span></Link><Link href="/cart"><ShoppingBag/><span>Keranjang<b>{cartCount} Produk</b></span>{cartCount>0&&<i>{cartCount}</i>}</Link></div></div></header>
 <nav className="market-nav"><div className="market-shell">{nav.map(x=><Link key={x.name} href={x.href}>{x.name}</Link>)}<a href="#promos">Promo</a></div></nav>
 <div className={`market-drawer ${menu?"open":""}`} aria-hidden={!menu}><div><button onClick={()=>setMenu(false)} aria-label="Tutup menu"><X/></button>{nav.map(x=><Link key={x.name} href={x.href} onClick={()=>setMenu(false)}>{x.name}<ChevronRight/></Link>)}</div><button className="market-drawer-back" onClick={()=>setMenu(false)} aria-label="Tutup menu"/></div>
 <div id="market-content" className="market-shell market-hero-layout"><aside className="market-sidebar"><b>Kategori Furniture</b>{categories.map(x=><Link key={x.name} href={x.href}><span>{x.name}</span><ChevronRight size={13}/></Link>)}</aside><section className="market-hero"><Image src="/images/hero/living-room.jpg" fill priority sizes="(max-width:900px) 100vw, 58vw" alt="Interior ruang keluarga Casen Living"/><div><small>KOLEKSI TERBARU</small><h1>Furniture Modern<br/>Untuk Setiap Ruang</h1><p>Nyaman, fungsional, dan tahan lama untuk rumah dan kantor Anda.</p><Link href="/products">Belanja Sekarang</Link></div><span className="market-dots"><b/><i/><i/></span></section><aside className="market-service-cards">{[[House,"Konsultasi Interior","Gratis konsultasi dengan tim kami."],[Wrench,"Custom Furniture","Sesuai ukuran dan kebutuhan Anda."],[Building2,"Pesanan Bisnis","Penawaran khusus untuk perusahaan."]].map(([Icon,title,copy])=>{const I=Icon as typeof House;return <article key={String(title)}><I/><div><b>{String(title)}</b><p>{String(copy)}</p><a href="#quote">Minta info</a></div></article>})}</aside></div>
 <section className="market-benefits"><div className="market-shell">{[[PackageCheck,"Material Berkualitas","Tahan lama dan aman"],[Truck,"Gratis Ongkir","Min. pembelian berlaku"],[CreditCard,"Pembayaran Aman","Transaksi terlindungi"],[Headphones,"Layanan Pelanggan","Siap membantu setiap hari"]].map(([Icon,title,copy])=>{const I=Icon as typeof Truck;return <article key={String(title)}><I/><p><b>{String(title)}</b><span>{String(copy)}</span></p></article>})}</div></section>
 <section id="promos" className="market-shell market-section"><Head title="Penawaran & Promo" action="Lihat Semua Promo"/><div className="market-promos">{[["Diskon Hingga","Sofa Pilihan","/images/categories/living.jpg","/products?category=Ruang%20Tamu"],["Harga Spesial","Set Meja Makan","/images/categories/dining.jpg","/products?category=Ruang%20Makan"],["Produk Baru","Koleksi Ruang Kerja","/images/categories/office.jpg","/products?category=Ruang%20Kerja"],["Clearance Sale","Lemari & Penyimpanan","/images/categories/storage.jpg","/products?category=Penyimpanan"]].map(([eyebrow,title,image,href])=><Link key={title} href={href} className="market-promo"><Image src={image} fill sizes="(max-width:700px) 75vw,25vw" alt={title}/><div><small>{eyebrow}</small><h3>{title}</h3><i><ArrowRight size={16}/></i></div></Link>)}</div></section>
 <section className="market-shell market-section"><Head title="Kategori Pilihan" action="Lihat Semua Kategori"/><div className="market-categories">{categoryCards.map(([name,image,href])=><Link key={name} href={href}><div><Image src={image} fill sizes="(max-width:700px) 50vw,17vw" alt={name}/></div><b>{name}</b></Link>)}</div></section>
 <section className="market-shell market-collection"><div className="market-collection-banners">{[["Perlengkapan Ruang Keluarga","Sofa, meja, kabinet untuk hunian nyaman.","/images/categories/living.jpg","/products?category=Ruang%20Tamu"],["Ruang Kerja Produktif","Meja kerja dan kursi untuk hari yang fokus.","/images/categories/office.jpg","/products?category=Ruang%20Kerja"]].map(([title,copy,image,href])=><Link key={title} href={href}><Image src={image} fill sizes="(max-width:850px) 100vw,38vw" alt={title}/><div><h2>{title}</h2><p>{copy}</p><span>Lihat Koleksi</span></div></Link>)}</div><div className="market-tiles">{tiles.map((name,i)=><Link href="/products" key={name}><Image src={categoryCards[i%6][1]} fill sizes="(max-width:700px) 50vw,14vw" alt={name}/><b>{name}</b></Link>)}</div></section>
 <section id="quote" className="market-shell market-quote"><Image src="/images/categories/office.jpg" fill sizes="100vw" alt="Ruang kerja Casen Living"/><div className="market-quote-copy"><h2>Kemudahan untuk Pembelian dalam Jumlah Besar</h2><p>Dapatkan penawaran untuk bisnis, proyek, dan kebutuhan perusahaan.</p></div><form onSubmit={e=>{e.preventDefault();setQuote(true);e.currentTarget.reset()}}><h3>Minta Penawaran untuk Supplier</h3><div><label>Nama Perusahaan<input required name="company" placeholder="Nama perusahaan"/></label><label>Email<input required type="email" placeholder="email@perusahaan.com"/></label></div><label>Jumlah Kebutuhan<select required defaultValue=""><option value="" disabled>Pilih estimasi kebutuhan</option><option>10 - 50 produk</option><option>51 - 100 produk</option><option>Lebih dari 100 produk</option></select></label><label>Pesan (Opsional)<textarea placeholder="Kebutuhan proyek Anda"/></label><button>Kirim Penawaran</button>{quote&&<output>Terima kasih. Tim Casen Living akan menghubungi Anda.</output>}</form></section>
 <section id="recommendations" className="market-shell market-section"><Head title="Rekomendasi Produk" action="Lihat Semua"/><div className="market-tabs" role="tablist">{["Terlaris","Produk Baru","Penawaran Spesial"].map(x=><button role="tab" aria-selected={tab===x} className={tab===x?"active":""} key={x} onClick={()=>setTab(x)}>{x}</button>)}</div><div className="market-products">{recommended.map(p=><article key={p.id}><div><Link href={`/products/${p.id}`}><Image src={p.image} fill sizes="(max-width:650px) 50vw,20vw" alt={p.name}/></Link><button aria-label={`Simpan ${p.name}`} onClick={()=>store.toggle(p.id)}><Heart size={16} fill={store.wishes.includes(p.id)?"currentColor":"none"}/></button></div><p>{p.category}</p><Link href={`/products/${p.id}`}><h3>{p.name}</h3></Link><span><Star size={12} fill="currentColor"/> {p.rating} <small>({p.reviews} ulasan)</small></span><b>{p.price}</b><button className="market-add" aria-label={`Tambah ${p.name}`} onClick={()=>store.add(p.id)}><ShoppingBag size={16}/></button></article>)}</div>{!recommended.length&&<p className="market-empty">Produk belum tersedia untuk pilihan ini.</p>}</section>
 <section className="market-extra"><div className="market-shell"><Head title="Layanan Tambahan Kami" action="Lihat Semua Layanan" href="#quote"/><div>{[[House,"Konsultasi Desain Interior","Diskusi kebutuhan ruang Anda."],[Wrench,"Custom Furniture","Sesuai ukuran yang dibutuhkan."],[PackageCheck,"Jasa Perakitan","Perakitan oleh tim kami."],[Headphones,"Garansi & Dukungan","Bantuan setelah pembelian."]].map(([Icon,title,copy])=>{const I=Icon as typeof House;return <article key={String(title)}><I/><span><b>{String(title)}</b><small>{String(copy)}</small></span></article>})}</div></div></section>
 <section id="regions" className="market-section"><div className="market-shell"><Head title="Supplier Berdasarkan Wilayah"/><div className="market-regions">{[["🇮🇩","Indonesia","Produk Lokal"],["🇨🇳","China","Perabot Modern"],["🇲🇾","Malaysia","Desain Kontemporer"],["🇻🇳","Vietnam","Harga Kompetitif"],["🇹🇭","Thailand","Keahlian Kayu"],["🇸🇬","Singapore","Teknologi & Inovasi"]].map(([flag,name,copy])=><article key={name}><b>{flag}</b><span>{name}<small>{copy}</small></span></article>)}</div></div></section>
 <footer id="market-footer"><div className="market-shell"><div className="market-foot-grid"><div><Link href="/" className="market-brand">Casen Living<small>WHERE SPACE BECOMES HOME</small></Link><p>Furniture berkualitas untuk setiap ruang, rumah dan tempat kerja.</p></div><div><h3>Belanja</h3><Link href="/products">Semua Produk</Link><Link href="/products?category=Ruang%20Tamu">Ruang Tamu</Link><Link href="/products?category=Kamar%20Tidur">Kamar Tidur</Link><Link href="/products?category=Ruang%20Kerja">Ruang Kerja</Link></div><div><h3>Layanan Pelanggan</h3><a href="#market-footer">Pusat Bantuan</a><Link href="/orders">Lacak Pesanan</Link><a href="#market-footer">Informasi Pengiriman</a><a href="#market-footer">Garansi Produk</a></div><div><h3>Dapatkan Update Terbaru</h3><p>Promo dan koleksi baru dari Casen Living.</p><form onSubmit={e=>{e.preventDefault();setNewsletter(true)}}><input required type="email" placeholder="Alamat email Anda"/><button aria-label="Daftar newsletter"><Send size={16}/></button></form>{newsletter&&<output>Terdaftar.</output>}</div></div></div><div className="market-bottom"><div className="market-shell"><span>© 2026 Casen Living. Semua hak dilindungi.</span><span><a href="#kebijakan-privasi">Kebijakan Privasi</a> · <b>BCA · Mandiri · BNI · VISA · Mastercard · OVO · DANA</b></span></div></div></footer>
 </main>
}
