"use client";
import Image from "next/image";
import Link from "next/link";
import { notFound } from "next/navigation";
import { use } from "react";
import { Heart, Star } from "lucide-react";
import { productById, relatedProducts } from "@/lib/catalog";
import { ProductCard, StoreFooter, StoreHeader, useStore } from "@/app/furniture/FurnitureShell";
import { AddToCartButton } from "@/components/AddToCartButton";
export default function ProductDetail({params}:{params:Promise<{id:string}>}){return <ProductLoader params={params}/>}
function ProductLoader({params}:{params:Promise<{id:string}>}){const store=useStore();const product=use(params);const item=productById(product.id);if(!item)notFound();const saved=store.wishes.includes(item.id);const related=relatedProducts(item);return <><StoreHeader store={store}/><main className="store-shell detail-page"><div className="detail-crumb"><Link href="/products">Produk</Link><span>/</span><span>{item.category}</span></div><section className="product-detail"><div className="detail-image"><Image src={item.image} fill priority sizes="(max-width: 800px) 100vw, 50vw" alt={item.name}/></div><div className="detail-copy"><p>{item.category}</p><h1>{item.name}</h1><div className="detail-rating"><Star size={16} fill="currentColor"/> {item.rating} <span>({item.reviews} ulasan)</span></div><strong>{item.price}</strong>{item.oldPrice&&<del>{item.oldPrice}</del>}<p className="detail-description">{item.description}</p><dl><div><dt>Material</dt><dd>{item.material}</dd></div><div><dt>Ukuran</dt><dd>{item.dimensions.join(' · ')}</dd></div><div><dt>Warna</dt><dd>{item.colors.join(', ')}</dd></div></dl><div className="detail-actions"><AddToCartButton onAdd={()=>store.add(item.id)} icon>Tambahkan ke Keranjang</AddToCartButton><button className={saved?'saved':''} aria-label="Simpan ke wishlist" onClick={()=>store.toggle(item.id)}><Heart size={18} fill={saved?'currentColor':'none'}/> Wishlist</button></div></div></section>{related.length>0&&<section className="related"><div className="related-head"><h2>Produk {item.relatedGroup==='sofa'?'sofa':item.relatedGroup==='desk'?'meja kerja':item.relatedGroup==='office-chair'?'kursi kerja':item.relatedGroup==='dining-table'?'meja makan':item.relatedGroup==='bed'?'tempat tidur':'serupa'} lainnya</h2><Link href={`/products?category=${encodeURIComponent(item.category)}`} className="related-all">Lihat Semua →</Link></div><div className="catalog-grid">{related.map(p=><ProductCard key={p.id} product={p} store={store}/>)}</div></section>}</main><StoreFooter/></>}
